"""Add password_hash field to User model

Revision ID: 186e85af2a9e
Revises: c27a4bd6e785
Create Date: 2025-07-06 04:43:59.899212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186e85af2a9e'
down_revision = 'c27a4bd6e785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
